### PR TITLE
Fix Nucleus export_predictions_generator not returning confidences

### PR DESCRIPTION
**Pull request by jaisanliang**
ix Nucleus export_predictions_generator not returning confidences - see https://www.google.com/url?q=https://scaleapi.slack.com/archives/C01PGG898J1/p1686940016031259&sa=D&source=docs&ust=1689803496342391&usg=AOvVaw3244pEsQvb7D1x-ue7ICew for context

`scaleapi` PR that also needs to be merged: https://github.com/scaleapi/scaleapi/pull/63564

Ticket: https://scale.atlassian.net/browse/FEDENG-4207

### CODE REVIEW

**Review by jean-lucas — APPROVED** [review]

**Review by jean-lucas — COMMENTED** [review]
lgtm on green CI

**Comment by jaisanliang** [comment]
> lgtm on green CI

@jean-lucas thanks for the review :D the CI passed, can you merge (and also review this related PR: https://github.com/scaleapi/scaleapi/pull/63564)

**Comment by jean-lucas** [comment]
@jaisanliang I just remembered, we need to update the version in the `pyproject.toml` file. Otherwise we won't be leverage the automatic pypi  release.

We can merge it once thats completed.

**Comment by jaisanliang** [comment]
@jean-lucas any idea why 2 tests started failing? they were passing before the most recent commits (which were just changelog edits)

**Comment by jean-lucas** [comment]
> @jean-lucas any idea why 2 tests started failing? they were passing before the most recent commits (which were just changelog edits)

@jaisanliang I'm not 100% sure whats going on, its possible a bad marge on the scaleapi repo went through. I'm taking a look

**Pull request merged**
