### PR TITLE
Rename Unit Test to Scenario Test in Nucleus

### PR DESCRIPTION
**Pull request by sasha-scale**
Rename unit test to scenario test in Python Client.  Corresponding scaleapi change: https://github.com/scaleapi/scaleapi/pull/35580

### CODE REVIEW

**Comment by sasha-scale** [comment]
Tests won't pass here until the scaleapi side is merged.  Run locally to prove they pass

**Review by phil-scale — APPROVED** [review]

**Comment by pfmark** [comment]
I saw you also did the renaming of the endpoints from `modelci` to `validate`. I'd propose to also do the rename to validate here. Wdyt?

**Comment by sasha-scale** [comment]
Ah I already did, but forgot to push the commit :)

**Comment by pfmark** [comment]
Awesome, thanks! :)

**Pull request merged**
